projectName: <ENTER>-tcp-java
templateRepo:
  remote: git@github.com:excellaco/tcp-java.git
  refName: master

variables:
  ProjectName: <project name in gradle settings>
  GroupName: <group name in gradle build>
  