# Config placeholder
projectName: [CHANGE ME]
templateRepo:
  remote: git@github.com:excellaco/[CHANGE ME].git
  refName: master

variables:
  aws_region: us-east-2
  project_name: [CHANGE ME]
  environment: dev
  