# Config template - all []' require filling in (and removing the []'s)
projectName: [CHANGE ME]
templateRepo:
  remote: git@github.com:excellaco/terraform-aws-jenkins-stack.git
  refName: master

variables:
  aws_region: [us-east-2]
  project_name: [CHANGE_ME] #mapped to terraform prefix var
  environment: dev
  