# Config template - all []' require filling in (and removing the []'s)
projectName: [project directory which will be created]
templateRepo:
  remote: git@github.com:excellaco/tcp-ecs.git
  refName: master

variables:
  github_token: [A token with access to your repos]
  aws_access_key: [your access key]
  aws_secret_key: [your secret key]
  aws_region: [region]
  aws_email: [your email address]
  
  # only alpha-numeric and dashes allowed
  project_name: [something-unique]
  environment: [dev]
  
  # needs to be unique per region
  project_key_name: [project_name_ENVIRONMENT_ssh_key_pair_YOURNAME]
  
  # Used for application database
  db_name: [tcp_ecs] #alpha-numeric
  db_username: [something] #alpha-numeric
  db_password: [anothergreatpassword] #>8 characters
  db_identifier: [tcp-ecs-db1] #lowercase, alpha-numeric
