# Config template - all []' require filling in (and removing the []'s)
projectName: [CHANGE ME]
templateRepo:
  remote: git@github.com:excellaco/terraform-aws-sonar-ecs-fargate.git
  refName: master

variables:
  github_token: [A token with access to your repos]
  aws_region: [us-east-2]
  project_name: [CHANGE_ME]
  environment: dev
  